services:
  hadoop:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: hadoop
    environment:
      - CLUSTER_NAME=single-node
    ports:
      - "50070:50070" # WebHDFS / Namenode UI
      - "8020:8020"   # HDFS RPC
    volumes:
      - hadoop_data:/hadoop/dfs
    networks:
      - bda-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.node
    container_name: bda-backend
    ports:
      - "8080:8080"
    environment:
      - HDFS_HOST=http://hadoop:50070
      - HDFS_USER=root
    depends_on:
      - hadoop
    networks:
      - bda-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.node
    container_name: bda-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - bda-network

volumes:
  hadoop_data:
    driver: local

networks:
  bda-network:
    driver: bridge