version: '3.7'

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    ports:
      - "9870:9870"
      - "9000:9000"
    environment:
      - CLUSTER_NAME=test

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    depends_on:
      - namenode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000

  backend:
    build: ./backend
    container_name: waste-backend
    ports:
      - "8000:8000"
    depends_on:
      - namenode
    environment:
      - HDFS_URL=http://namenode:50070
      - HDFS_USER=root

  frontend:
    build: ./frontend
    container_name: waste-frontend
    ports:
      - "8080:80"
